language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn test
  - yarn run build


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PERSONAL_TOKEN
  local_dir: build
  on:
    branch: prod