language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn install

jobs:
  include:
    - stage: test
      script: yarn test

    - stage: deploy
      script: yarn run build
      provider: pages
      skip_cleanup: true
      github_token: $PERSONAL_TOKEN
      local_dir: build
      target_branch: prod
      if: branch = prod


stages:
  - test
  - deploy